version: '3.8'
services:
  frontend:
    build:
      context: ./Front-end
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"  # Expose the container port to the host, adjust if necessary

  backend:
    build:
      context: ./Back-end
      dockerfile: Dockerfile.backend
    ports:
      - "5100:5100"  # Expose the container port to the host, adjust if necessary

  database:
    image: postgres:latest
    environment:
      - DATABASE_URL=postgres://postgres:Welikechess1234@db.zvtbsbscwazqnadhpfvv.supabase.co:6543/postgres?pgbouncer=true
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "6543:6543"
