version: '3.8'
services:
  backend:
    build:
      context: ./Back-end/tornelo-back-end
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5000"
    depends_on:
      - database

  frontend:
    build:
      context: ./Front-end/tornelo-front-end
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"

  database:
    image: postgres:latest
    environment:
      - DATABASE_URL=postgres://postgres:Welikechess1234@db.zvtbsbscwazqnadhpfvv.supabase.co:6543/postgres?pgbouncer=true
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "6543:6543"