# Use a Node.js base image
FROM node:latest

# Set the working directory in the container
WORKDIR /app

# Set the POSTGRES_HOST_AUTH_METHOD environment variable
ENV POSTGRES_HOST_AUTH_METHOD=trust

# Copy package files and install dependencies
COPY TORNELOFINAL/Back-end/package.json /app/
RUN yarn install

# Copy the rest of the application files
COPY . .

# Expose the port the app runs on
EXPOSE 5000

# Define the command to start the app
CMD ["npm", "start"]