version: "3.9"

services:
  front-end:
    build: ./tornelo-front-end
    ports:
      - "8080:8080"
    depends_on:
      - back-end

  back-end:
    build: ./tornelo-back-end
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  database:
    # the image provides the imagage from DockerHub to run
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
